# Generated by Django 6.1 on 2026-08-28 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='extra_context_link',
            new_name='yt_video_link',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='language',
            new_name='topic_name',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
        migrations.CreateModel(
            name='CommumityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('short_description', models.CharField(default='', max_length=355)),
                ('resource_link', models.URLField(blank=True, null=True)),
                ('yt_video_link', models.URLField(blank=True, null=True)),
                ('sub_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityResourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/resource_images')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.resource')),
            ],
        ),
        migrations.DeleteModel(
            name='ResourceImage',
        ),
    ]
