# Generated by Django 6.1 on 2026-08-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_extra_context_link_resource_yt_video_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityresourceimage',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.commumityresource'),
        ),
    ]
