# Generated by Django 6.1 on 2026-08-29 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_communityresourceimage_resource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommumityResource',
            new_name='CommunityResource',
        ),
    ]
