# Generated by Django 6.1 on 2026-08-29 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_commumityresource_communityresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityresourceimage',
            name='image',
            field=models.ImageField(upload_to='resource_images'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='core.topic'),
        ),
    ]
