# Generated by Django 6.1 on 2026-08-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_communityresource_sub_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_resources', to='core.subtopic'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_resources', to='core.topic'),
        ),
    ]
