# Generated by Django 6.1 on 2026-08-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_resource_sub_topic_alter_resource_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_image',
            field=models.ImageField(default=1, upload_to='topic_images/'),
            preserve_default=False,
        ),
    ]
