# Generated by Django 6.1 on 2026-08-30 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_topic_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='sub_topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_resources', to='core.subtopic'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_resources', to='core.topic'),
        ),
    ]
