# Generated by Django 6.1 on 2026-08-30 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_resource_sub_topic_alter_resource_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='sub_topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_resource', to='core.subtopic'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_resource', to='core.topic'),
        ),
    ]
