# Generated by Django 6.1 on 2026-09-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_resource_sub_topic_alter_resource_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='official_doc_link',
            field=models.URLField(default='https://docs.djangoproject.com/en/6.1/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_link',
            field=models.URLField(default='https://docs.djangoproject.com/en/6.1/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='yt_video_link',
            field=models.URLField(default='https://docs.djangoproject.com/en/6.1/'),
            preserve_default=False,
        ),
    ]
