# Generated by Django 6.1 on 2026-09-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_resource_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_resource', to='core.topic'),
        ),
    ]
